name: mas-competition-frontend-deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci --force
      
      - name: Build
        run: npm run build

      - name: Prepare staging directory
        run: |
          rm -rf '/var/mas/staging/'
          mkdir '/var/mas/staging/'
          cp -r build/* '/var/mas/staging/'
