name: mas-competition-frontend-deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Prepare staging directory
        run: |
          echo ${{ secrets.USERPWD }} | sudo -S rm -rf '/var/mas/staging/'
          echo ${{ secrets.USERPWD }} | sudo -S mkdir '/var/mas/staging/'
          echo ${{ secrets.USERPWD }} | sudo -S cp -r build/* '/var/mas/staging/'
