name: mas-competition-frontend-deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: echo $(pwd)
      - run: npm ci
      - run: npm run build
      - run: rm -rf '/var/mas/staging/'
      - run: cp -r build/* '/var/mas/staging/'
      
      
