name: mas-competition-frontend-deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: rm -rf '/var/mas/staging/'
      - uses: actions/checkout@v4
        with:
          path: './staging'
      - run: cd './staging'
      - run: npm ci
      - run: npm run build
      - run: cp -r build/* '/var/mas/staging/'
      
      
